apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: default
  labels:
    app: demo-app
    component: config
data:
  # Application configuration
  NODE_ENV: "production"
  PORT: "8080"
  APP_VERSION: "1.0.0"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30s"
  HEALTH_CHECK_TIMEOUT: "5s"
  
  # Application settings
  REQUEST_TIMEOUT: "30s"
  MAX_REQUEST_SIZE: "10mb"
  
  # Feature flags
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "false"
