name: Build, Push, and Deploy to EKS

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TF_VERSION: 1.13.0
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-west-2' }}
  CENTRAL_BACKEND_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Build and test the application
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Install dependencies
      working-directory: ./app
      run: npm ci
    - name: Run linting
      working-directory: ./app
      run: npm run lint || true
    - name: Run tests
      working-directory: ./app
      run: npm test || true
    - name: Build application
      working-directory: ./app
      run: npm run build || true

  # Get infrastructure info (kept as-is for EKS cluster, domain, repo n
